# Generated by Django 6.0.4 on 2026-05-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='anonima',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('analise', 'Em análise'), ('resolvida', 'Resolvida')], default='recebida', max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('moral', 'Assédio Moral'), ('sexual', 'Assédio Sexual'), ('abuso', 'Abuso de Poder')], max_length=20),
        ),
    ]
