# Generated by Django 6.0.4 on 2026-05-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_denuncia_anonima_denuncia_status_alter_denuncia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='resposta_rh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
