# Generated by Django 6.0.4 on 2026-05-14 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='denuncia',
            name='exibir_setor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='link_anexo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnexoDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='anexos_denuncias/')),
                ('link', models.URLField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.denuncia')),
            ],
        ),
        migrations.AddField(
            model_name='denuncia',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='denuncias.setor'),
        ),
    ]
