# Generated by Django 6.0.4 on 2026-05-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_feedbackia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('moral', 'Assédio Moral'), ('sexual', 'Assédio Sexual'), ('abuso', 'Abuso de Poder'), ('discriminacao', 'Discriminação'), ('ameaca', 'Ameaça'), ('violencia', 'Violência'), ('outros', 'Outros')], max_length=20),
        ),
    ]
