# Generated by Django 6.0.4 on 2026-05-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0008_alter_denuncia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='gravidade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='baixa', max_length=20),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
