# Generated by Django 6.0.4 on 2026-05-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0009_denuncia_gravidade_denuncia_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='prioridade_ia',
            field=models.IntegerField(default=1),
        ),
    ]
