# Generated by Django 6.0.4 on 2026-05-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0010_denuncia_prioridade_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='resumo_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
