# Generated by Django 6.0.4 on 2026-05-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0011_denuncia_resumo_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='arquivada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='data_arquivamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
