# Generated by Django 6.0.4 on 2026-05-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0012_denuncia_arquivada_denuncia_data_arquivamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexodenuncia',
            name='motivo_status_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anexodenuncia',
            name='status_link',
            field=models.CharField(blank=True, choices=[('seguro', 'Aparentemente seguro'), ('suspeito', 'Suspeito'), ('perigoso', 'Potencialmente perigoso')], max_length=20, null=True),
        ),
    ]
