# Generated by Django 6.0.4 on 2026-05-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0013_anexodenuncia_motivo_status_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexodenuncia',
            name='motivo_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
