# Generated by Django 6.0.4 on 2026-05-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0015_chatdenuncia_mensagemchatdenuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemchatdenuncia',
            name='link_detectado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemchatdenuncia',
            name='motivo_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemchatdenuncia',
            name='status_link',
            field=models.CharField(blank=True, choices=[('seguro', 'Aparentemente seguro'), ('suspeito', 'Suspeito'), ('perigoso', 'Potencialmente perigoso')], max_length=20, null=True),
        ),
    ]
