# Generated by Django 6.0.4 on 2026-05-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0016_mensagemchatdenuncia_link_detectado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoMensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='anexos_chat/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='denuncias.mensagemchatdenuncia')),
            ],
        ),
    ]
