# Generated by Django 6.0.4 on 2026-06-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0017_anexomensagemchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='trocar_senha_primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mensagemchatdenuncia',
            name='tipo_autor',
            field=models.CharField(choices=[('funcionario', 'Funcionário'), ('rh', 'RH'), ('sistema', 'Sistema')], max_length=20),
        ),
    ]
