# Generated by Django 6.0.4 on 2026-06-02 23:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0018_perfilusuario_trocar_senha_primeiro_acesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='criado_pelo_rh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='trocar_senha_primeiro_acesso',
            field=models.BooleanField(default=False),
        ),
    ]
